# server
server:
  port: 8050

# spring
spring:
  application:
    name: spring-cloud-zuul

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

# zuul
zuul:
  routes:
    app-a:
      path: /user/**
      serviceId: consumer-hystrix

# logging
logging:
  level:
    root: info