# server
server:
  port: 8050

# spring
spring:
  application:
    name: spring-cloud-zuul

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

# zuul
zuul:
  ignored-services: '*'
  routes:
    app-user:
      path: /user/**
      serviceId: consumer-hystrix
    app-sidecar:
      path: /sidecar/**
      serviceId: spring-cloud-sidecar

# logging
logging:
  level:
    root: info