# server(eureka默认端口为:8761)
server:
  port: 8761

# spring
spring:
  application:
    name: spring-cloud-server

# eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # eureka服务器的地址(注意：地址最后的 /eureka 是固定的)
      defaultZone: http://user:password123@localhost:${server.port}/eureka

# logging
logging:
  level:
    root: info