# server
server:
  port: 8070

# spring
spring:
  application:
    name: spring-cloud-sidecar

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

# sidecar
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json

# logging
logging:
  level:
    root: info