# server
server:
  port: 8010

# spring
spring:
  application:
    name: consumer-client

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

# logging
logging:
  level:
    root: info