# server
server:
  port: 7900

# spring
spring:
  application:
    name: provider-user

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

# logging
logging:
  level:
    root: info